# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

def firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '8.12.1-beta'
  pod 'FirebaseStorage', '~> 8.12'
end

target 'Inflow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  firebase

  # Pods for Inflow

  target 'InflowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InflowUITests' do
    # Pods for testing
  end

end
